server:
  port: 6001
eureka:
  instance:
    hostname: localhost
  client:
#  不向注册中心注册自己
#    registerWithEureka: false
#    不去检索服务
#    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:6002/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
#    自我保护模式关闭
    enable-self-preservation: false
