server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
zuul:
  routes:
    feign-consumer: feign-consumerzuul
    feign-ribbon-provider1: feign-ribbon-provider1
ribbon:
  ReadTimeout: 100
  ConnectTimeout: 10
feign-ribbon-provider1:
  ribbon:
    ReadTimeout: 100
    ConnectTimeout: 10
#    默认不为注册中心的所有服务自动创建路由规则
#    ignored-services: *

