server:
  port: 8009
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
# ribbon 全局配置
ribbon.ConnectTimeout: 500
ribbon.ReadTimeout: 500
#指定服务配置
feign-ribbon-provider.ribbon.ConnectTimeout: 500
feign-ribbon-provider.ribbon.ReadTimeout: 500